name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.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 }}
          USERNAME: ${{ github.HydraDVV }}
      - name: Commit & Push
        run: |
          git config user.name HydraDVV
          git config user.email yildizarda654@gmail.com
          git add -A .
          git commit -m "generated"
          git push
